### ISSUE TITLE
Question - Setting Config

### ISSUE THREAD

**Issue by nwoodcl** [XRM-OSS/D365-PowerKanban#37]
I have read the section on configuration but unsure from the documentation on how to publish the config json files? Do I create then as a web resource? do I add them to the pcf solution that I publish? if so then where.

Thanks for your help

**Comment by DigitalFlow** [comment]
Hi @nwoodcl,

The JSON configs are not created as webresources. You need to create them as PowerKanban Config records, which is a CRM entity. This is also described [here](https://github.com/XRM-OSS/D365-PowerKanban/wiki/Configuration#basic-configuration)

**Comment by nwoodcl** [comment]
Thanks @DigitalFlow 
I was installing the PCF control from source and not installing the managed solution, so no CRM entities where created.
Do you have details on creating the entities or an unmanaged solution containing just the framework in CRM to support the control?

**Comment by DigitalFlow** [comment]
Hi @nwoodcl,

why not use the managed solution? This has various advantages, such as being able to uninstall everything with one click.
There is an unmanaged solution available [here](https://github.com/XRM-OSS/D365-PowerKanban/tree/master/export).
I would not recommend using this if your reasoning is not making a contribution, unmanaged solutions don't offer any benefit otherwise.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
I'll close this issue as you should be able to install everything using the unmanaged solution that I linked.
Please reopen if issues persist.
