### ISSUE TITLE
Issue: Default View and Fit Lanes to screen width not working

### ISSUE THREAD

**Issue by pab74** [XRM-OSS/D365-PowerKanban#45]
Hello Florian,
Merry Xmas :-)
I just downloaded the last version of PowerKanban. It seems that Default View and fitLanesToScreenWidth are not working.
When I use the following config file, the default view is "My All Tasks" and not "All Tasks" and I see just 3 lanes and not all 4 lanes. I attached also a screenshot.
Any idea?
Thank you very much for your great job

{
    "primaryEntity": {
        "allowTransitions": true,
        "logicalName": "task",
        "swimLaneSource": "speedy_taskstatus",
        "transitionCallback": "boardViewExtender.onStateTransition"
    },
"fitLanesToScreenWidth": true,
    "defaultView": "All Tasks",
    "showCreateButton": true,
    "showDeleteButton": true,
    "showDeactivateButton": true
}
![image](https://user-images.githubusercontent.com/5435158/103176821-4f13c000-4875-11eb-8aa5-8eb2b0870929.png)

**Comment by DigitalFlow** [comment]
Hi @pab74,

I wish you merry christmas as well :christmas_tree: 
fitLanesToScreenWidth and defaultView both need to be set _inside_ primaryEntity or secondaryEntity.
There is a JSON scheme available here: https://github.com/XRM-OSS/D365-PowerKanban/wiki/Configuration#json-scheme
When you pass this into the online JSON schema validator, it helps you to build your config: https://www.jsonschemavalidator.net/

Your config as it is prints 5 errors:
![image](https://user-images.githubusercontent.com/4287938/103178295-de26d500-4881-11eb-9595-9d7b24fde995.png)

When you correct it like below, it shows no errors anymore:
```JSON
{
"primaryEntity": {
"allowTransitions": true,
"logicalName": "task",
"swimLaneSource": "speedy_taskstatus",
"transitionCallback": "boardViewExtender.onStateTransition",
"fitLanesToScreenWidth": true,
"defaultView": "All Tasks",
}
}
```

I hope to include an editor which already validates the JSON schema in the near future, so that the config is validated directly on the form.

Kind Regards,
Florian

**Comment by pab74** [comment]
Thank you Florian,
you are right and my JSON was wrong. I swear I checked before posting on
Github, but it seems my check with the validator was wrong :-)
Sorry for bothering you.
Have a great holiday ahead :-)
Paolo

Il giorno dom 27 dic 2020 alle ore 20:28 Florian Krönert <
notifications@github.com> ha scritto:

**Comment by DigitalFlow** [comment]
Hi Paolo,

Yes I believe you that you checked :)
In fact I did a negative check as well before posting my response and noticed that no errors were shown.
This was due to the JSON manifest allowing additional properties.

I fixed this and now the validation in the top level will not allow any properties that are not explicitly defined.
Wish you great holidays as well. :)

Kind Regards, 
Florian
