### ISSUE TITLE
Records sort order from view is not respected

### ISSUE THREAD

**Issue by BugsOli** [XRM-OSS/D365-PowerKanban#59]
Hi again @DigitalFlow,

With the latest release, I've found out that the sort order is not respected anymore, for example in this picture:
![image](https://user-images.githubusercontent.com/40055851/113001380-0cfa6300-9171-11eb-9269-916195c723ef.png)

In release 0.9.20, the latest "modified on" records were always on top in each lane, therefore the 3rd case should be on top (it's the latest updated); since release 0.9.22, the sort order from the view is not taken into account anymore.

Also, I've checked the latest code and it shows that the "defaultView" property has been removed from the "primaryEntity" in the configuration, is it by design? I think it's quite handy to have different configurations targeting different views based on how the different teams work with the Kanban.

Thanks for your time,

Oli

**Comment by DigitalFlow** [comment]
Hi @BugsOli,

thanks for creating this issue.

You're right, I did not see that sorting was broken.
We moved from the integrated view selector to using the default view selector that CRM provides.
This gets rid of quite a few limitations that we had and integrates way better into the system.

You can still use the PowerKanban on different views. Once you open PowerKanban, you can switch views with the default view selector above PowerKanban. For different teams working with PowerKanban, every team can use the pin feature and pin their most important view as their default view.

Unfortunately it is not (yet) possible to switch the view of the dataset from within a PCF, which is why I had to remove the default view on the primary entity.

I'll fix the sorting issue as soon as possible, we can still debate on the defaultView topic I guess.

Kind regards,
Florian

**Comment by BugsOli** [comment]
Hello @DigitalFlow,

You are totally right! This new way of using the views is actually a lot more flexible in the way that I can now associate any config I want directly in the view's custom control 👍
This is a better approach I think, and the fact that the user can now decide which view he/she wants to "pin" is better than having a user's configuration stored somewhere...

Thanks a lot,

Oli

**Comment by BugsOli** [comment]
@DigitalFlow 

Works like a charm in the latest release, thanks for the quick fix!

Oli

**Comment by DigitalFlow** [comment]
Hi @BugsOli,

great to hear :) Thanks again for reporting that fast.
I'll close this issue.

Kind regards,
Florian
