### ISSUE TITLE
Does Power Kanban abide by Model Driven App selected views and pinned views

### ISSUE THREAD

**Issue by Mcai282** [XRM-OSS/D365-PowerKanban#62]
Hi,

Another quick question. Does Power Kanban abide by what you set as your pinned view? Say if I pinned an original system view and then added this control to that view for opportunities will navigating to opps default to that view in a kanban format?

I've also got a custom Model Driven app which I've turned off/removed all other opportunity system views except for 4 views. The thing is when I switch over to Kanban it loads all the other views regardless of what I've selected in the model driven app designer.

**Comment by DigitalFlow** [comment]
Hi @Mcai282,

it sounds as if you're not on the latest release.
Can you try updating to release v0.9.24? Since this release PowerKanban uses purely the default Dynamics view selector for the primary entity, so your model driven app view filtering and pinned default views will work.

Kind Regards,
Florian

**Comment by Mcai282** [comment]
> Hi @Mcai282,
> 
> it sounds as if you're not on the latest release.
> Can you try updating to release v0.9.24? Since this release PowerKanban uses purely the default Dynamics view selector for the primary entity, so your model driven app view filtering and pinned default views will work.
> 
> Kind Regards,
> Florian

Brilliant!! Thanks Florian,

Works perfectly! You're a legend!
