### ISSUE TITLE
What happens if there are more than 250 records

### ISSUE THREAD

**Issue by Mcai282** [XRM-OSS/D365-PowerKanban#63]
Hi there!

Another quick question. What happens when the kanban is set on a view that displays more than 250 records (the max you can set to display in a normal view). 

I noticed the records displayed conforms to a user's personal settings of how many records they want to view per page but what happens if it's over say 250 records. Can we still use the search bar to find records not displayed in the kanban? Noticed when I set the records per page to 50 for a list with 200 records, it can't find the ones not on the page.

Kind regards,
Mike

**Comment by DigitalFlow** [comment]
Hi @Mcai282,

previously PowerKanban showed really all data for a view.

Recently we switched to a more streamlined integration of PowerKanban, where we used the integrated view selector of Dynamics for selecting the primary view.
Usually there should be code for fetching all pages of the view. But if it really behaves as you described, this seems to have been broken because of the update.
I'll look deeper into it, the designed behaviour should be that PowerKanban shows all data of a view. Then the search should work as well.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @Mcai282,

in v0.9.25, up to 5000 records are fetched: https://github.com/XRM-OSS/D365-PowerKanban/releases/tag/v0.9.25
This behaviour should have been in there from the very first start, but broke during one of the last updates.

Kind Regards,
Florian

**Comment by Mcai282** [comment]
Hi @DigitalFlow . Thank you so much! You're a legend!

**Comment by DigitalFlow** [comment]
Hi @Mcai282,

thanks a lot, I'm glad you like it.
In the mean time I noticed there was a race condition in the previous release, please update to v0.9.27: https://github.com/XRM-OSS/D365-PowerKanban/releases/tag/v0.9.27.

I'll close this issue :)

Kind Regards,
Florian
