### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by surfmaverick** [XRM-OSS/D365-PowerKanban#75]
I am working on custom styling.  I am reading the docs and would like to better understand what this means in the documentation: "All card form data can be found in context.data".

Can someone please elaborate. Basically what I am trying to do is run the script on a different field found on the incident record.

**Comment by DigitalFlow** [comment]
Hi @surfmaverick,

as stated in the other thread, all fields that you put in your card form will be fetched.
All the fetched data will be available in `context.data` for every record.

Does that help you?

Kind regards,
Florian

**Comment by surfmaverick** [comment]
It does yes. What is the name of the field. I am somewhat confused why the example starts with “context.data.oss_”. 

I have a field on the card that has a logical name of “new_duedate”. Would the address name be “context.data.oss_new_duedate”?

**Comment by DigitalFlow** [comment]
Hi @surfmaverick,

no it would just be `context.data.new_duedate`.
The `oss_` prefix is just because I did my examples with my oss publisher.

You can also always add break points to your custom scripts and debug with your browser's debugger, nothing special about how the scripts are loaded or executed.

Kind regards,
Florian

**Comment by surfmaverick** [comment]
Thanks.  That helped.
